### ISSUE TITLE
error on conenction

### ISSUE THREAD

**Issue by brett005** [tankibaj/Vicidial-Admin-App-PHP-OOP#1]
`Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'asterisk.pathaocs' doesn't exist' in /var/www/html/Monitor/vendor/usmanhalalit/pixie/src/Pixie/QueryBuilder/QueryBuilderHandler.php:144 Stack trace: #0 /var/www/html/Monitor/vendor/usmanhalalit/pixie/src/Pixie/QueryBuilder/QueryBuilderHandler.php(144): PDO->prepare('SELECT * FROM `...') #1 /var/www/html/Monitor/vendor/usmanhalalit/pixie/src/Pixie/QueryBuilder/QueryBuilderHandler.php(174): Pixie\QueryBuilder\QueryBuilderHandler->statement('SELECT * FROM `...', Array) #2 /var/www/html/Monitor/vendor/usmanhalalit/pixie/src/Pixie/QueryBuilder/QueryBuilderHandler.php(193): Pixie\QueryBuilder\QueryBuilderHandler->get() #3 /var/www/html/Monitor/includes/Auth.php(27): Pixie\QueryBuilder\QueryBuilderHandler->first() #4 /var/www/html/Monitor/login.php(24): Common\Auth->checkLogin('admin', 'batgirl963963') #5 {main} thrown in /var/www/html/Monitor/vendor/usmanhalalit/pixie/src/Pixie/QueryBuilder/QueryBuilderHandler.php on line 144`

**Comment by brett005** [comment]
`<?php
/**
 * Created by PhpStorm.
 * User: elomelo
 * Date: 24/4/18
 * Time: 5:14 PM
 */

$config = array(
    'driver'    => 'mysqli', // Db driver
    'host'      => 'localhost',
    'database'  => 'asterisk',
    'username'  => 'cron',
    'password'  => '1234',
    'charset'   => 'utf8', // Optional
    'collation' => 'utf8_unicode_ci', // Optional
    'prefix'    => '', // Table prefix, optional
    'options'   => array( // PDO constructor options, optional
        PDO::ATTR_TIMEOUT => 5,
        PDO::ATTR_EMULATE_PREPARES => false,
    ),
);

try{
    new \Pixie\Connection('mysql', $config, 'PATHAODB');
}catch(Exception $e){
    die($e->getMessage());
}

?>`

**Comment by shyam-maurya** [comment]
This page isn’t working (server ip)  is currently unable to handle this request.
HTTP ERROR 500

**Comment by sonilux** [comment]
Same Problem

[Mon Dec 02 04:31:15.793919 2019] [php5:error] [pid 22509] [client 190.196.119.185:52634] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'asterisk.pathaocs' doesn't exist' in /srv/www/htdocs/vicidial/menu/vendor/usmanhalalit/pixie/src/Pixie/QueryBuilder/QueryBuilderHandler.php:144\nStack trace:\n#0 /srv/www/htdocs/vicidial/menu/vendor/usmanhalalit/pixie/src/Pixie/QueryBuilder/QueryBuilderHandler.php(144): PDO->prepare('SELECT * FROM `...')\n#1 /srv/www/htdocs/vicidial/menu/vendor/usmanhalalit/pixie/src/Pixie/QueryBuilder/QueryBuilderHandler.php(174): Pixie\\QueryBuilder\\QueryBuilderHandler->statement('SELECT * FROM `...', Array)\n#2 /srv/www/htdocs/vicidial/menu/vendor/usmanhalalit/pixie/src/Pixie/QueryBuilder/QueryBuilderHandler.php(193): Pixie\\QueryBuilder\\QueryBuilderHandler->get()\n#3 /srv/www/htdocs/vicidial/menu/includes/Auth.php(27): Pixie\\QueryBuilder\\QueryBuilderHandler->first()\n#4 /srv/www/htdocs/vicidial/menu/login.php(24): Common\\Auth->checkLogin('sonilux', 'oikjokj')\n#5 {main}\n  thrown in /srv/www/htdocs/vicidial/menu/vendor/usmanhalalit/pixie/src/Pixie/QueryBuilder/QueryBuilderHandler.php on line 144, referer: mysite

**Comment by sujan-subedi** [comment]
Can not login, do you reckon we need to create an empty database as pathaocs with some tables in it? I tried changing that to asterisk.vicidial_users and now the error isn't there but whenever user tries to login, it says " Incorrect username / password ", could be the md5 hash for the password, or something similar. Please shed some light as to how to get this working, it'll be much appreciated.
